<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesTableSeeder extends Seeder
{
    public function run()
    {

        $cities = [
            [
                'lang' => 'en',
                'title_en' => 'Riyadh',
                'title_ar' => 'الرياض',
                'slug_en' => 'riyadh',
                'slug_ar' => 'الرياض',
                'h1_en' => 'Training courses in Riyadh',
                'h1_ar' => 'دورات تدريبية في الرياض',
                'description_en' => 'Training Lane offers a range of courses in Riyadh designed to enhance professional skills, including project management and leadership training, as well as offering courses in digital marketing and data analysis to meet the demands of the evolving job market in the city.',
                'description_ar' => 'تقدم Training Lane مجموعة من الدورات التدريبية في الرياض المصممة لتعزيز المهارات المهنية، بما في ذلك دورات في إدارة المشاريع والتدريب على القيادة، بالإضافة إلى تقديم دورات في التسويق الرقمي وتحليل البيانات لتلبية متطلبات سوق العمل المتطور في المدينة.',
                'meta_title_en' => 'Riyadh - Capital of Saudi Arabia',
                'meta_description_en' => 'Learn more about Riyadh, the capital of Saudi Arabia.',
                'meta_keywords_en' => 'Riyadh, Saudi Arabia, Capital',
                'meta_robots_en' => 'index,follow',
                'meta_type_en' => 'website',
                'meta_site_name_en' => 'Riyadh Site',
                'meta_site_en' => 'www.riyadh.com',
                'meta_local_en' => 'en_US',
                'meta_card_en' => 'summary_large_image',
                'meta_title_ar' => 'الرياض - عاصمة المملكة العربية السعودية',
                'meta_description_ar' => 'تعرف على المزيد حول الرياض، عاصمة المملكة العربية السعودية.',
                'meta_keywords_ar' => 'الرياض، المملكة العربية السعودية، العاصمة',
                'meta_robots_ar' => 'index,follow',
                'meta_type_ar' => 'website',
                'meta_site_name_ar' => 'موقع الرياض',
                'meta_site_ar' => 'www.riyadh.com',
                'meta_local_ar' => 'ar_SA',
                'meta_card_ar' => 'summary_large_image',
                'meta_image_size' => '1200x630',
                'image_alt_en' => 'Riyadh cityscape',
                'image_alt_ar' => 'مشهد مدينة الرياض',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lang' => 'en',
                'title_en' => 'Jeddah',
                'title_ar' => 'جدة',
                'slug_en' => 'jeddah',
                'slug_ar' => 'جدة',
                'h1_en' => 'Training courses in Jeddah',
                'h1_ar' => 'دورات تدريبية في جدة',
                'description_en' => 'Training Lane offers a range of courses in Jeddah designed to enhance professional skills, including project management and leadership training, as well as offering courses in digital marketing and data analysis to meet the demands of the evolving job market in the city.',
                'description_ar' => 'تقدم Training Lane مجموعة من الدورات التدريبية في جدة المصممة لتعزيز المهارات المهنية، بما في ذلك دورات في إدارة المشاريع والتدريب على القيادة، بالإضافة إلى تقديم دورات في التسويق الرقمي وتحليل البيانات لتلبية متطلبات سوق العمل المتطور في المدينة.',
                'meta_title_en' => 'Jeddah - Gateway to Mecca',
                'meta_description_en' => 'Discover training opportunities in Jeddah, a major urban center in Saudi Arabia.',
                'meta_keywords_en' => 'Jeddah, Saudi Arabia, Courses',
                'meta_robots_en' => 'index,follow',
                'meta_type_en' => 'website',
                'meta_site_name_en' => 'Jeddah Site',
                'meta_site_en' => 'www.jeddah.com',
                'meta_local_en' => 'en_US',
                'meta_card_en' => 'summary_large_image',
                'meta_title_ar' => 'جدة - بوابة مكة',
                'meta_description_ar' => 'اكتشف فرص التدريب في جدة، مركز حضري رئيسي في المملكة العربية السعودية.',
                'meta_keywords_ar' => 'جدة، المملكة العربية السعودية، دورات',
                'meta_robots_ar' => 'index,follow',
                'meta_type_ar' => 'website',
                'meta_site_name_ar' => 'موقع جدة',
                'meta_site_ar' => 'www.jeddah.com',
                'meta_local_ar' => 'ar_SA',
                'meta_card_ar' => 'summary_large_image',
                'meta_image_size' => '1200x630',
                'image_alt_en' => 'Jeddah cityscape',
                'image_alt_ar' => 'مشهد مدينة جدة',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lang' => 'en',
                'title_en' => 'Al Khobar',
                'title_ar' => 'الخبر',
                'slug_en' => 'al-khobar',
                'slug_ar' => 'الخبر',
                'h1_en' => 'Training courses in Al Khobar',
                'h1_ar' => 'دورات تدريبية في الخبر',
                'description_en' => 'Training Lane offers a range of courses in Al Khobar designed to enhance professional skills, including project management and leadership training, as well as offering courses in digital marketing and data analysis to meet the demands of the evolving job market in the city.',
                'description_ar' => 'تقدم Training Lane مجموعة من الدورات التدريبية في الخبر المصممة لتعزيز المهارات المهنية، بما في ذلك دورات في إدارة المشاريع والتدريب على القيادة، بالإضافة إلى تقديم دورات في التسويق الرقمي وتحليل البيانات لتلبية متطلبات سوق العمل المتطور في المدينة.',
                'meta_title_en' => 'Al Khobar - Economic Hub',
                'meta_description_en' => 'Discover professional training courses in Al Khobar, a key economic hub in Saudi Arabia.',
                'meta_keywords_en' => 'Al Khobar, Saudi Arabia, Courses',
                'meta_robots_en' => 'index,follow',
                'meta_type_en' => 'website',
                'meta_site_name_en' => 'Al Khobar Site',
                'meta_site_en' => 'www.al-khobar.com',
                'meta_local_en' => 'en_US',
                'meta_card_en' => 'summary_large_image',
                'meta_title_ar' => 'الخبر - مركز اقتصادي',
                'meta_description_ar' => 'اكتشف الدورات التدريبية المهنية في الخبر، مركز اقتصادي رئيسي في المملكة العربية السعودية.',
                'meta_keywords_ar' => 'الخبر، المملكة العربية السعودية، دورات',
                'meta_robots_ar' => 'index,follow',
                'meta_type_ar' => 'website',
                'meta_site_name_ar' => 'موقع الخبر',
                'meta_site_ar' => 'www.al-khobar.com',
                'meta_local_ar' => 'ar_SA',
                'meta_card_ar' => 'summary_large_image',
                'meta_image_size' => '1200x630',
                'image_alt_en' => 'Al Khobar cityscape',
                'image_alt_ar' => 'مشهد مدينة الخبر',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lang' => 'en',
                'title_en' => 'Medina',
                'title_ar' => 'المدينة المنورة',
                'slug_en' => 'medina',
                'slug_ar' => 'المدينة-المنورة',
                'h1_en' => 'Training courses in Medina',
                'h1_ar' => 'دورات تدريبية في المدينة المنورة',
                'description_en' => 'Training Lane offers a range of courses in Medina designed to enhance professional skills, including project management and leadership training, as well as offering courses in digital marketing and data analysis to meet the demands of the evolving job market in the city.',
                'description_ar' => 'تقدم Training Lane مجموعة من الدورات التدريبية في المدينة المنورة المصممة لتعزيز المهارات المهنية، بما في ذلك دورات في إدارة المشاريع والتدريب على القيادة، بالإضافة إلى تقديم دورات في التسويق الرقمي وتحليل البيانات لتلبية متطلبات سوق العمل المتطور في المدينة.',
                'meta_title_en' => 'Medina - The Radiant City',
                'meta_description_en' => 'Learn about the training courses available in Medina, a historic and significant city in Saudi Arabia.',
                'meta_keywords_en' => 'Medina, Saudi Arabia, Courses',
                'meta_robots_en' => 'index,follow',
                'meta_type_en' => 'website',
                'meta_site_name_en' => 'Medina Site',
                'meta_site_en' => 'www.medina.com',
                'meta_local_en' => 'en_US',
                'meta_card_en' => 'summary_large_image',
                'meta_title_ar' => 'المدينة المنورة - المدينة المضيئة',
                'meta_description_ar' => 'تعرف على الدورات التدريبية المتاحة في المدينة المنورة، مدينة تاريخية وهامة في المملكة العربية السعودية.',
                'meta_keywords_ar' => 'المدينة المنورة، المملكة العربية السعودية، دورات',
                'meta_robots_ar' => 'index,follow',
                'meta_type_ar' => 'website',
                'meta_site_name_ar' => 'موقع المدينة المنورة',
                'meta_site_ar' => 'www.medina.com',
                'meta_local_ar' => 'ar_SA',
                'meta_card_ar' => 'summary_large_image',
                'meta_image_size' => '1200x630',
                'image_alt_en' => 'Medina cityscape',
                'image_alt_ar' => 'مشهد مدينة المدينة المنورة',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        DB::table('cities')->insert($cities);
    }
}
