<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesTableSeeder extends Seeder
{
    public function run()
    {

        $cities = [
            [
                'lang' => 'en',
                'title' => 'Riyadh',
                'slug' => 'riyadh',
                'h1' => 'Training courses in Riyadh',
                'description' => 'Training Lane offers a range of courses in Riyadh designed to enhance professional skills, including project management and leadership training, as well as offering courses in digital marketing and data analysis to meet the demands of the evolving job market in the city.',
                'meta_title' => 'Riyadh - Capital of Saudi Arabia',
                'meta_description' => 'Learn more about Riyadh, the capital of Saudi Arabia.',
                'meta_keywords' => 'Riyadh, Saudi Arabia, Capital',
                'meta_robots' => 'index,follow',
                'meta_type' => 'website',
                'meta_site_name' => 'Riyadh Site',
                'meta_site' => 'www.riyadh.com',
                'meta_local' => 'en_US',
                'meta_card' => 'summary_large_image',
                'meta_image_size' => '1200x630',
                'image_alt' => 'Riyadh cityscape',
                'image_title' => 'Riyadh cityscape',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'lang' => 'ar',
                'title' => 'الرياض',
                'slug' => 'الرياض',
                'h1' => 'دورات تدريبية في الرياض',
                'description' => 'تقدم Training Lane مجموعة من الدورات التدريبية في الرياض المصممة لتعزيز المهارات المهنية، بما في ذلك دورات في إدارة المشاريع والتدريب على القيادة، بالإضافة إلى تقديم دورات في التسويق الرقمي وتحليل البيانات لتلبية متطلبات سوق العمل المتطور في المدينة.',
                'meta_title' => 'الرياض - عاصمة المملكة العربية السعودية',
                'meta_description' => 'تعرف على المزيد حول الرياض، عاصمة المملكة العربية السعودية.',
                'meta_keywords' => 'الرياض، المملكة العربية السعودية، العاصمة',
                'meta_robots' => 'index,follow',
                'meta_type' => 'website',
                'meta_site_name' => 'موقع الرياض',
                'meta_site' => 'www.riyadh.com',
                'meta_local' => 'ar_SA',
                'meta_card' => 'summary_large_image',
                'meta_image_size' => '1200x630',
                'image_alt' => 'مشهد مدينة الرياض',
                'image_title' => 'مشهد مدينة الرياض',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'lang' => 'en',
                'title' => 'Jeddah',
                'slug' => 'jeddah',
                'h1' => 'Training courses in Jeddah',
                'description' => 'Training Lane offers a range of courses in Jeddah designed to enhance professional skills, including project management and leadership training, as well as offering courses in digital marketing and data analysis to meet the demands of the evolving job market in the city.',
                'meta_title' => 'Jeddah - Gateway to Mecca',
                'meta_description' => 'Discover training opportunities in Jeddah, a major urban center in Saudi Arabia.',
                'meta_keywords' => 'Jeddah, Saudi Arabia, Courses',
                'meta_robots' => 'index,follow',
                'meta_type' => 'website',
                'meta_site_name' => 'Jeddah Site',
                'meta_site' => 'www.jeddah.com',
                'meta_local' => 'en_US',
                'meta_card' => 'summary_large_image',
                'meta_image_size' => '1200x630',
                'image_alt' => 'Jeddah cityscape',
                'image_title' => 'Jeddah cityscape',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'lang' => 'ar',
                'title' => 'جدة',
                'slug' => 'جدة',
                'h1' => 'دورات تدريبية في جدة',
                'description' => 'تقدم Training Lane مجموعة من الدورات التدريبية في جدة المصممة لتعزيز المهارات المهنية، بما في ذلك دورات في إدارة المشاريع والتدريب على القيادة، بالإضافة إلى تقديم دورات في التسويق الرقمي وتحليل البيانات لتلبية متطلبات سوق العمل المتطور في المدينة.',
                'meta_title' => 'جدة - بوابة مكة',
                'meta_description' => 'اكتشف فرص التدريب في جدة، مركز حضري رئيسي في المملكة العربية السعودية.',
                'meta_keywords' => 'جدة، المملكة العربية السعودية، دورات',
                'meta_robots' => 'index,follow',
                'meta_type' => 'website',
                'meta_site_name' => 'موقع جدة',
                'meta_site' => 'www.jeddah.com',
                'meta_local' => 'ar_SA',
                'meta_card' => 'summary_large_image',
                'meta_image_size' => '1200x630',
                'image_alt' => 'مشهد مدينة جدة',
                'image_title' => 'مشهد مدينة جدة',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'lang' => 'en',
                'title' => 'Al Khobar',
                'slug' => 'al-khobar',
                'h1' => 'Training courses in Al Khobar',
                'description' => 'Training Lane offers a range of courses in Al Khobar designed to enhance professional skills, including project management and leadership training, as well as offering courses in digital marketing and data analysis to meet the demands of the evolving job market in the city.',
                'meta_title' => 'Al Khobar - Economic Hub',
                'meta_description' => 'Discover professional training courses in Al Khobar, a key economic hub in Saudi Arabia.',
                'meta_keywords' => 'Al Khobar, Saudi Arabia, Courses',
                'meta_robots' => 'index,follow',
                'meta_type' => 'website',
                'meta_site_name' => 'Al Khobar Site',
                'meta_site' => 'www.al-khobar.com',
                'meta_local' => 'en_US',
                'meta_card' => 'summary_large_image',
                'meta_image_size' => '1200x630',
                'image_alt' => 'Al Khobar cityscape',
                'image_title' => 'Al Khobar cityscape title',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'lang' => 'ar',
                'title' => 'الخبر',
                'slug' => 'الخبر',
                'h1' => 'دورات تدريبية في الخبر',
                'description' => 'تقدم Training Lane مجموعة من الدورات التدريبية في الخبر المصممة لتعزيز المهارات المهنية، بما في ذلك دورات في إدارة المشاريع والتدريب على القيادة، بالإضافة إلى تقديم دورات في التسويق الرقمي وتحليل البيانات لتلبية متطلبات سوق العمل المتطور في المدينة.',
                'meta_title' => 'الخبر - مركز اقتصادي',
                'meta_description' => 'اكتشف الدورات التدريبية المهنية في الخبر، مركز اقتصادي رئيسي في المملكة العربية السعودية.',
                'meta_keywords' => 'الخبر، المملكة العربية السعودية، دورات',
                'meta_robots' => 'index,follow',
                'meta_type' => 'website',
                'meta_site_name' => 'موقع الخبر',
                'meta_site' => 'www.al-khobar.com',
                'meta_local' => 'ar_SA',
                'meta_card' => 'summary_large_image',
                'meta_image_size' => '1200x630',
                'image_alt' => 'مشهد مدينة الخبر',
                'image_title' => 'مشهد مدينة الخبر ',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'lang' => 'en',
                'title' => 'Medina',
                'slug' => 'medina',
                'h1' => 'Training courses in Medina',
                'description' => 'Training Lane offers a range of courses in Medina designed to enhance professional skills, including project management and leadership training, as well as offering courses in digital marketing and data analysis to meet the demands of the evolving job market in the city.',
                'meta_title' => 'Medina - The Radiant City',
                'meta_description' => 'Learn about the training courses available in Medina, a historic and significant city in Saudi Arabia.',
                'meta_keywords' => 'Medina, Saudi Arabia, Courses',
                'meta_robots' => 'index,follow',
                'meta_type' => 'website',
                'meta_site_name' => 'Medina Site',
                'meta_site' => 'www.medina.com',
                'meta_local' => 'en_US',
                'meta_card' => 'summary_large_image',
                'meta_image_size' => '1200x630',
                'image_alt' => 'Medina cityscape',
                'image_title' => 'Medina cityscape',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'lang' => 'ar',
                'title' => 'المدينة المنورة',
                'slug' => 'المدينة-المنورة',
                'h1' => 'دورات تدريبية في المدينة المنورة',
                'description' => 'تقدم Training Lane مجموعة من الدورات التدريبية في المدينة المنورة المصممة لتعزيز المهارات المهنية، بما في ذلك دورات في إدارة المشاريع والتدريب على القيادة، بالإضافة إلى تقديم دورات في التسويق الرقمي وتحليل البيانات لتلبية متطلبات سوق العمل المتطور في المدينة.',
                'meta_title' => 'المدينة المنورة - المدينة المضيئة',
                'meta_description' => 'تعرف على الدورات التدريبية المتاحة في المدينة المنورة، مدينة تاريخية وهامة في المملكة العربية السعودية.',
                'meta_keywords' => 'المدينة المنورة، المملكة العربية السعودية، دورات',
                'meta_robots' => 'index,follow',
                'meta_type' => 'website',
                'meta_site_name' => 'موقع المدينة المنورة',
                'meta_site' => 'www.medina.com',
                'meta_local' => 'ar_SA',
                'meta_card' => 'summary_large_image',
                'meta_image_size' => '1200x630',
                'image_alt' => 'مشهد مدينة المدينة المنورة',
                'image_title' => 'مشهد مدينة المدينة المنورة',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        DB::table('cities')->insert($cities);
    }
}
