<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MetaSeeder extends Seeder
{
    public function run()
    {
        $metas = [
            [
                'section' => 1,
                'meta_title_en' => 'Welcome to Our Home Page',
                'meta_description_en' => 'Discover the best content on our home page.',
                'meta_keywords_en' => 'home, welcome, content',
                'meta_robots_en' => 'index, follow',
                'meta_type_en' => 'website',
                'meta_site_name_en' => 'SiteName',
                'meta_site_en' => 'https://www.sitename.com',
                'meta_local_en' => 'en_US',
                'meta_card_en' => 'Summary of Home Page',

                'meta_title_ar' => 'مرحبا بكم في صفحتنا الرئيسية',
                'meta_description_ar' => 'اكتشف أفضل المحتويات في صفحتنا الرئيسية.',
                'meta_keywords_ar' => 'الصفحة الرئيسية, مرحبا, محتوى',
                'meta_robots_ar' => 'index, follow',
                'meta_type_ar' => 'website',
                'meta_site_name_ar' => 'اسم الموقع',
                'meta_site_ar' => 'https://www.sitename.com',
                'meta_local_ar' => 'ar_SA',
                'meta_card_ar' => 'ملخص الصفحة الرئيسية',
            ],
            [
                'section' => 2,
                'meta_title_en' => 'Explore Our Categories',
                'meta_description_en' => 'Find a variety of categories to suit your needs.',
                'meta_keywords_en' => 'categories, explore, variety',
                'meta_robots_en' => 'index, follow',
                'meta_type_en' => 'website',
                'meta_site_name_en' => 'SiteName',
                'meta_site_en' => 'https://www.sitename.com',
                'meta_local_en' => 'en_US',
                'meta_card_en' => 'Summary of Categories',

                'meta_title_ar' => 'استكشاف فئاتنا',
                'meta_description_ar' => 'اكتشف مجموعة متنوعة من الفئات لتناسب احتياجاتك.',
                'meta_keywords_ar' => 'فئات, استكشاف, تنوع',
                'meta_robots_ar' => 'index, follow',
                'meta_type_ar' => 'website',
                'meta_site_name_ar' => 'اسم الموقع',
                'meta_site_ar' => 'https://www.sitename.com',
                'meta_local_ar' => 'ar_SA',
                'meta_card_ar' => 'ملخص الفئات',
            ],
            [
                'section' => 3,
                'meta_title_en' => 'Browse Our Courses',
                'meta_description_en' => 'Learn more about our wide range of courses.',
                'meta_keywords_en' => 'courses, learning, education',
                'meta_robots_en' => 'index, follow',
                'meta_type_en' => 'website',
                'meta_site_name_en' => 'SiteName',
                'meta_site_en' => 'https://www.sitename.com',
                'meta_local_en' => 'en_US',
                'meta_card_en' => 'Summary of Courses',

                'meta_title_ar' => 'تصفح دوراتنا',
                'meta_description_ar' => 'تعرف على المزيد حول مجموعة واسعة من الدورات التدريبية لدينا.',
                'meta_keywords_ar' => 'دورات, تعلم, تعليم',
                'meta_robots_ar' => 'index, follow',
                'meta_type_ar' => 'website',
                'meta_site_name_ar' => 'اسم الموقع',
                'meta_site_ar' => 'https://www.sitename.com',
                'meta_local_ar' => 'ar_SA',
                'meta_card_ar' => 'ملخص الدورات',
            ],
            [
                'section' => 4,
                'meta_title_en' => 'Our Venues',
                'meta_description_en' => 'Explore the various venues we offer.',
                'meta_keywords_en' => 'venues, locations, explore',
                'meta_robots_en' => 'index, follow',
                'meta_type_en' => 'website',
                'meta_site_name_en' => 'SiteName',
                'meta_site_en' => 'https://www.sitename.com',
                'meta_local_en' => 'en_US',
                'meta_card_en' => 'Summary of Venues',

                'meta_title_ar' => 'مواقعنا',
                'meta_description_ar' => 'استكشف المواقع المختلفة التي نقدمها.',
                'meta_keywords_ar' => 'مواقع, مواقع, استكشاف',
                'meta_robots_ar' => 'index, follow',
                'meta_type_ar' => 'website',
                'meta_site_name_ar' => 'اسم الموقع',
                'meta_site_ar' => 'https://www.sitename.com',
                'meta_local_ar' => 'ar_SA',
                'meta_card_ar' => 'ملخص المواقع',
            ],
            [
                'section' => 5,
                'meta_title_en' => 'Latest Blogs',
                'meta_description_en' => 'Stay updated with our latest blog posts.',
                'meta_keywords_en' => 'blogs, news, updates',
                'meta_robots_en' => 'index, follow',
                'meta_type_en' => 'website',
                'meta_site_name_en' => 'SiteName',
                'meta_site_en' => 'https://www.sitename.com',
                'meta_local_en' => 'en_US',
                'meta_card_en' => 'Summary of Blogs',

                'meta_title_ar' => 'أحدث المدونات',
                'meta_description_ar' => 'ابق على اطلاع بآخر منشورات المدونة لدينا.',
                'meta_keywords_ar' => 'مدونات, أخبار, تحديثات',
                'meta_robots_ar' => 'index, follow',
                'meta_type_ar' => 'website',
                'meta_site_name_ar' => 'اسم الموقع',
                'meta_site_ar' => 'https://www.sitename.com',
                'meta_local_ar' => 'ar_SA',
                'meta_card_ar' => 'ملخص المدونات',
            ],
            [
                'section' => 6,
                'meta_title_en' => 'Contact Us',
                'meta_description_en' => 'Get in touch with us for any queries.',
                'meta_keywords_en' => 'contact, support, help',
                'meta_robots_en' => 'index, follow',
                'meta_type_en' => 'website',
                'meta_site_name_en' => 'SiteName',
                'meta_site_en' => 'https://www.sitename.com',
                'meta_local_en' => 'en_US',
                'meta_card_en' => 'Summary of Contact Us',

                'meta_title_ar' => 'اتصل بنا',
                'meta_description_ar' => 'تواصل معنا لأي استفسارات.',
                'meta_keywords_ar' => 'اتصال, دعم, مساعدة',
                'meta_robots_ar' => 'index, follow',
                'meta_type_ar' => 'website',
                'meta_site_name_ar' => 'اسم الموقع',
                'meta_site_ar' => 'https://www.sitename.com',
                'meta_local_ar' => 'ar_SA',
                'meta_card_ar' => 'ملخص اتصل بنا',
            ],
            [
                'section' => 7,
                'meta_title_en' => 'About Us',
                'meta_description_en' => 'Learn more about our mission and values.',
                'meta_keywords_en' => 'about us, mission, values',
                'meta_robots_en' => 'index, follow',
                'meta_type_en' => 'website',
                'meta_site_name_en' => 'SiteName',
                'meta_site_en' => 'https://www.sitename.com',
                'meta_local_en' => 'en_US',
                'meta_card_en' => 'Summary of About Us',

                'meta_title_ar' => 'من نحن',
                'meta_description_ar' => 'تعرف على المزيد حول مهمتنا وقيمنا.',
                'meta_keywords_ar' => 'من نحن, مهمة, قيم',
                'meta_robots_ar' => 'index, follow',
                'meta_type_ar' => 'website',
                'meta_site_name_ar' => 'اسم الموقع',
                'meta_site_ar' => 'https://www.sitename.com',
                'meta_local_ar' => 'ar_SA',
                'meta_card_ar' => 'ملخص من نحن',
            ],
            [
                'section' => 8,
                'meta_title_en' => 'City Categories',
                'meta_description_en' => 'Explore categories by city.',
                'meta_keywords_en' => 'city, categories, explore',
                'meta_robots_en' => 'index, follow',
                'meta_type_en' => 'website',
                'meta_site_name_en' => 'SiteName',
                'meta_site_en' => 'https://www.sitename.com',
                'meta_local_en' => 'en_US',
                'meta_card_en' => 'Summary of City Categories',

                'meta_title_ar' => 'فئات المدينة',
                'meta_description_ar' => 'استكشف الفئات حسب المدينة.',
                'meta_keywords_ar' => 'مدينة, فئات, استكشاف',
                'meta_robots_ar' => 'index, follow',
                'meta_type_ar' => 'website',
                'meta_site_name_ar' => 'اسم الموقع',
                'meta_site_ar' => 'https://www.sitename.com',
                'meta_local_ar' => 'ar_SA',
                'meta_card_ar' => 'ملخص فئات المدينة',
            ],
        ];

        DB::table('metas')->insert($metas);
    }
}
